### ISSUE TITLE
Wondering if you are going to make this repository private?

### ISSUE THREAD

**Issue by edf42001** [davidbernat/work-summer-2019#2]

**Comment by davidbernat** [comment]
Yep.

**Comment by davidbernat** [comment]
Thanks Ethan. I’m going to add you to the Slack channel (we rarely use it)
and show you a cool tool for connecting Github to slack.

Enjoy your vacation. If you feel like it, motivated by your own self
curiosity for discovery, read the documents. I’ll be around to answer your
questions.

If you ever need anything immediately for whatever reason, you can always
text me or WhatsApp me. 917-825-7193
